//
//  Lists.h
//  Cast Lots
//
//  Created by Andy Uyeda on 7/7/17.
//  Copyright © 2017 Andy Uyeda. All rights reserved.
//

#ifndef Lists_h
#define Lists_h

#define ELDERS @[@"Ryan Fullerton", \
@"Jeff King", \
@"Donnie Isely", \
@"Ward Young", \
@"Andy Morris", \
@"Evan Calvin", \
@"Ramny Perez", \
@"Ben Hedrick", \
@"Doug Sturgeon", \
@"Dominic Cedillo", \
@"Jonny Atkinson", \
@"Jones Ndzi", \
@"Matthew Huested", \
@"Jay Ingram", \
@"Trevor Komatsu", \
@"Shingsay Lee", \
@"Tom Scott"]

#define GCGLEADERS @[@"Cody Prichard", \
@"Daniel Taylor", \
@"Daniel Trevino & Miguel Contreras", \
@"Jones Ndzi", \
@"Robbie Simmons", \
@"Matt Doby", \
@"Nick Paola", \
@"Brian Scyphers & Albert Oh", \
@"David Bankes", \
@"Dave Rennalls & Shaun Martens", \
@"Kenny Fields", \
@"Jared Heinz", \
@"Andrew Perkins & Deeds Burlager", \
@"Jason Cashell", \
@"Josh Yuen & Van Michael Komatsu", \
@"Andres Vera & Kevin Gabriel", \
@"Anthony Leitner", \
@"Ben Fennell", \
@"Ben Hedrick & Ross Parmly", \
@"Donnie Isely", \
@"Ethan Ammon & Alex Jacobs", \
@"James Bufkin", \
@"Jay Ingram & Jim Hedrick", \
@"Jeremy Pelton", \
@"Josh Ramirez", \
@"Josh Ruud", \
@"Matt Mihelic", \
@"Rob Lauter", \
@"Shingsay Lee", \
@"Aaron Burkhart", \
@"Andy Bryant", \
@"Cody Gardner & Michael Lambelet", \
@"David Tyrell", \
@"Jeremy Corkum", \
@"Jordan Friesen", \
@"Kenny & Chris Komatsu", \
@"Kevin Gue", \
@"Mike Withers & Shawn Lopes", \
@"Nick Platt", \
@"Mike Stringer", \
@"Shawn Langley & Drue Corbett", \
@"Tim Winters", \
@"Chris Walker & Adam Denton", \
@"Blake Scheideman", \
@"Biven Toma & Seth Osborne"]

#define MEMBERS  @[ @"Jacob Adams", \
@"Amanullah Afzali", \
@"Ghonchagul Afzali", \
@"Hajara Mary Afzali", \
@"Khatema Jeniffer Afzali", \
@"Luke Hedaiatullah Afzali", \
@"Silsila Sosan Afzali", \
@"Charles Aina", \
@"Chavon Aina", \
@"Allison Allen", \
@"Craig Allen", \
@"Emily Allen", \
@"Keith Allen", \
@"Alexis Ammon", \
@"Ethan Ammon", \
@"Aaron An", \
@"Bob Anerson", \
@"Jody Anderson", \
@"Kristi Apostel", \
@"Shawn Apostel", \
@"Rachel Archer", \
@"Lucas Ardelean", \
@"Melissa Ardelean", \
@"Chello Armbrister", \
@"Celeste Arnett", \
@"AJ Aspinwall", \
@"Jordan Aspinwall", \
@"Janaye Atkinson", \
@"Jonny Atkinson", \
@"Josh Austin", \
@"Eric Awbrey", \
@"Dylan Bailey", \
@"Rebecca Bailey", \
@"William Ballentine", \
@"Amy Bankes", \
@"David Bankes", \
@"Kelly Bankes", \
@"Josh Barrentine", \
@"Zoe Barrow", \
@"Jordan Basore", \
@"Cassie Bastidas", \
@"Hannah Baugh", \
@"Michael Becker", \
@"Sydney Becker", \
@"Rene Bentsen", \
@"Scott Bentsen", \
@"Josh Berner", \
@"Meghan Berner", \
@"Caitlin Blaylock", \
@"Richard Blaylock", \
@"Taylor Blount", \
@"Tyler Blount", \
@"Jake Bradley", \
@"Amanda Brainard", \
@"Ben Brainard", \
@"DuJuan Brents", \
@"Quincy Brents", \
@"Ramonia Brents", \
@"Kristen Brewer", \
@"Sam Brewer", \
@"Joseph Bridges", \
@"Nathan Brown", \
@"Matthew Browning", \
@"Andy Bryant", \
@"Sarah Bryant", \
@"Becky Burke", \
@"Jared Burke", \
@"Kearstie Burke", \
@"Mike Burke", \
@"India Bufkin", \
@"James Bufkin", \
@"Aaron Burkhart", \
@"Melissa Burkhart", \
@"Deeds Burlager", \
@"Spenser Burlager", \
@"Emily Burns", \
@"Kris Burns", \
@"Greg Buth", \
@"Lora Buth", \
@"Rosie Buzzy", \
@"Emily Byrd", \
@"Charlie Cai", \
@"Evan Calvin", \
@"Kristin Carlton", \
@"Casey Cashell", \
@"Jason Cashell", \
@"Kristan Castro", \
@"Linh Castro", \
@"Dominic Cedillo", \
@"Rebecca Cedillo", \
@"Stephanie Chavez", \
@"Samantha Cheng", \
@"Jack Cissna", \
@"Sydnee Cissna", \
@"Carrie Cole", \
@"Ryan Cole", \
@"Shannon Collins", \
@"Gregory Collins", \
@"Andrew Colson", \
@"Nicole Colson", \
@"Whitney Conely", \
@"Kara Contreras", \
@"Miguel Contreras", \
@"Lindsey Cook", \
@"Drue Corbett", \
@"Evi Corbett", \
@"Anna Corkum", \
@"Jeremy Corkum", \
@"Cherise Cosby", \
@"Whitney Craven", \
@"Karen Culler", \
@"Karen Danka", \
@"AJ Davis", \
@"Matt Deaver", \
@"Trista Deaver", \
@"Maggie DeLoye", \
@"Adam Denton", \
@"Kellie Denton", \
@"Allison Detrick", \
@"Dean Dickens", \
@"Laura Doby", \
@"Matt Doby", \
@"Adam Dorsey", \
@"Tyriesha Doyle", \
@"Eric Dubois", \
@"Kaitlin Dubois", \
@"Scott Dukes", \
@"Jon Dunn", \
@"Rachel Edwards", \
@"Samuel Edwards", \
@"Kyle Eiswald", \
@"Rebekah Enarson", \
@"Jennifer Ennis", \
@"Mark Ennis", \
@"Alexis Estephan", \
@"Bernard Estephan", \
@"Brenda Estephan", \
@"Charbel Estephan", \
@"Massiel Estephan", \
@"Glen Evans", \
@"Tami Evans", \
@"Anna Farthing", \
@"Cody Farthing", \
@"Ben Fennell", \
@"Naomi Fennell", \
@"Sam Ferrell", \
@"Kenny Fields", \
@"Lisa Fields", \
@"Kristy Fletcher", \
@"Zach Fletcher", \
@"Mary Beth Fletcher", \
@"Gloria Forsythe", \
@"Abigail Fox", \
@"Kyle Fox", \
@"Eliza Frenette", \
@"Jeremy Frenette", \
@"Jordan Friesen", \
@"Mary Friesen", \
@"Christen Fuller", \
@"Christy Fullerton", \
@"Jordana Fullerton", \
@"Luke Fullerton", \
@"Ryan Fullerton", \
@"Christine Gabriel", \
@"Kevin Gabriel", \
@"Ashley Gardner", \
@"Cody Gardner", \
@"Evan Gartman", \
@"Ben German", \
@"Francesca Ghiorso", \
@"Keelie Gilbert", \
@"Carrie Gladstone", \
@"R.J. Gladstone", \
@"Furman Glenn", \
@"Kayla Godbold", \
@"Aaron Gohlke", \
@"Heidi Gorbandt", \
@"Caleb Graves", \
@"Jordan Graves", \
@"Kat Green", \
@"Sean Green", \
@"Kimberly Greenwell", \
@"Dylan Greer", \
@"Kaitlyn Greer", \
@"Katlyn Griffin", \
@"Amy Gue", \
@"Bethany Gue", \
@"Bonnie Gue", \
@"Kevin Gue", \
@"Charles Gue", \
@"Johnny Gue", \
@"Beth Gurtner", \
@"Dan Gurtner", \
@"Astrid Hacker", \
@"Stacey Hadler", \
@"Robert Hagerman", \
@"Samantha Hagerman", \
@"Christian Halbert", \
@"Miranda Hale", \
@"Ashley Hall", \
@"Noah Hall", \
@"Curtis Hall", \
@"Donna Hall", \
@"Katie Hancock", \
@"David Hare", \
@"Stacey Hare", \
@"Lenny Hartono", \
@"Charlotte Hazelwood", \
@"Ben Hedrick", \
@"Sarah Hedrick", \
@"Karis Hedrick", \
@"Tamara Hedrick", \
@"Jim Hedrick", \
@"Lee Ann Hedrick", \
@"Jared Heinz", \
@"Meredith Heinz", \
@"Sarah Hemby", \
@"Chris Henderson", \
@"Chelsea Hilbert", \
@"Bethany Hildebrand", \
@"Josh Hildebrand", \
@"Amy Hirby", \
@"Danny Hirby", \
@"Joanne Hirby", \
@"Melissa Hoagland", \
@"Stephen Hoagland", \
@"James Holfinger", \
@"Whitney Holsteen", \
@"Aaron Holt", \
@"Felicity Holt", \
@"Yohan Hong", \
@"Derek Hougland", \
@"Christina House", \
@"Jeremy House", \
@"Donghui Hu", \
@"Aleasha Huested", \
@"Hannah Huested", \
@"Matthew Huested", \
@"Will Hulsey", \
@"Amy Ingram", \
@"Jay Ingram", \
@"Becca Isely", \
@"Donnie Isely", \
@"Linda Isham", \
@"Wayne Isham", \
@"Dani Jackson", \
@"Jon Jackson", \
@"Susan Jacobi", \
@"Alex Jacobs", \
@"Lindsey Jacobs", \
@"Melissa Jacobs", \
@"Delaney Jacobs", \
@"Valerie Jillson", \
@"Sarah Jones", \
@"Nicole Joslin", \
@"Emily Juhl", \
@"Dave Kan", \
@"Jess Kan", \
@"Stacey Kandel", \
@"Josh Kary", \
@"Julie Kary", \
@"Steve Keating", \
@"Valarie Keating", \
@"Rosa Kim", \
@"Andrew King", \
@"Lauren King", \
@"Jeff King", \
@"Christy King", \
@"Alexis King", \
@"Corbin Kitzmiller", \
@"Melanie Kitzmiller", \
@"Kathryn Klein", \
@"Matthew Klein", \
@"Brandi Knapper", \
@"Michael Knapper", \
@"Amber Komatsu", \
@"Trevor Komatsu", \
@"Kenny Komatsu", \
@"Sarah Komatsu", \
@"Shawna Komatsu", \
@"Chris Komatsu", \
@"Van Michael Komatsu", \
@"Eric Krahwinkel", \
@"Hayley Krahwinkel", \
@"Samantha Kritner", \
@"Amber Kunce", \
@"Kyle Francis", \
@"Gary Lamb", \
@"Jessica Lamb", \
@"Emily Lambelet", \
@"Michael Lambelet", \
@"Meredith Langley", \
@"Shawn Langley", \
@"Hannah Larkins", \
@"Rob Lauter", \
@"Sarah Lauter", \
@"Jamie LeBon", \
@"Jared LeBon", \
@"Shingsay Lee", \
@"Pakou Lee", \
@"Anthony Leitner", \
@"Ashton Leitner", \
@"Dallas Leitner", \
@"Nicole Liesmaki", \
@"Anna Limanti", \
@"Lance Limanti", \
@"Hanna Lindsey", \
@"Josh Lohnes", \
@"Tadongrenia Longkumer", \
@"Shawn Lopes", \
@"Heidi Lopes", \
@"Herson Lopez", \
@"Yoany Lorenzo", \
@"Austin Loveing", \
@"Holly Loveing", \
@"Margo Loveing", \
@"Wanda Lowe", \
@"Jacob Lucio", \
@"Rebecca Luna", \
@"Wayne Luna", \
@"Joy Lynn", \
@"Tom Lynn", \
@"Jonathan Lyons", \
@"Claire Maday", \
@"Ronald Maday", \
@"Josiah Makram", \
@"Vilma Makram", \
@"Yaser Makram", \
@"Shania Mangum", \
@"Imran Manzoor", \
@"Rubina Manzoor", \
@"Amy Marcum", \
@"Charlie Marcum", \
@"Bonnie Marcum", \
@"Esther Marcum", \
@"Justice Marcum", \
@"Worthy Marcum", \
@"Lindsay Marsee", \
@"Timmy Marsee", \
@"Madelyn Martens", \
@"Shaun Martens", \
@"Dylan Matthews", \
@"Jessica Matthews", \
@"Evan Matthews", \
@"Kali Matthews", \
@"Joel Maupin", \
@"Abigail McBroom", \
@"Nathan McBroom", \
@"Alexis McDowell", \
@"Corey McGalliard", \
@"Sarah McGalliard", \
@"Hunter McGiveney", \
@"Evan McIntosh", \
@"Jena McIntosh", \
@"Bethany Meacham", \
@"Jonathan Meacham", \
@"Abbey Medley", \
@"Ethan Medley", \
@"Rachel Melson", \
@"Zack Melvin", \
@"Laura Metcalf", \
@"Phil Metcalf", \
@"Beth Michiemo", \
@"Tim Michiemo", \
@"Matt Mihelic", \
@"Larry Millikan", \
@"Jonathan Mompoint", \
@"Blut Moo", \
@"Bethany Moore", \
@"Glen Moore", \
@"Andy Morris", \
@"Emily Morris", \
@"Lazarus Morris", \
@"Anna Morris", \
@"Miriam Morris", \
@"Laurelen Muller", \
@"Michael Muller", \
@"Matt Nagel", \
@"Lisa Nagel", \
@"Abrianna Nagel", \
@"Kelly Nall", \
@"Chaney Nall", \
@"Jones Ndzi", \
@"Nicoline Ndzi", \
@"Eric Nerby", \
@"Kayla Nerby", \
@"Lori Nettles", \
@"Robert Nettles", \
@"Stephen O'Bryan", \
@"Barbara O'Bryan", \
@"Albert Oh", \
@"Sara Oh", \
@"Crissi Oldham", \
@"Joy Oliver", \
@"Kenny Oliver", \
@"Seth Osborne", \
@"Nick Paola", \
@"Sarah Paola", \
@"Josh Parker", \
@"Juliann Parmly", \
@"Ross Parmly", \
@"Jeremy Pelton", \
@"Lyndsey Pelton", \
@"Markell Pence", \
@"Baylee Pendleton", \
@"John Pendleton", \
@"Ramny Perez", \
@"Dayi Perez", \
@"Chris Pergola", \
@"Andrew Perkins", \
@"Rachel Perkins", \
@"Liane Peters", \
@"Gloria Peterson", \
@"Kristin Peterson", \
@"Luke Peterson", \
@"Clarissa Phillips", \
@"Peter Phillips", \
@"Andy Pittman", \
@"Josh Pittman", \
@"Courtney Platt", \
@"Nick Platt", \
@"Allison Pratt", \
@"Zach Pratt", \
@"Cody Prichard", \
@"Erica Prichard", \
@"Latevia Priddy", \
@"Joel Purvis", \
@"Abbey Ramirez", \
@"Josh Ramirez", \
@"Josh Rarick", \
@"Jeff Rarick", \
@"Joan Rarick", \
@"Janet Reimer", \
@"Curtis Reimer", \
@"Dave Rennalls", \
@"Jen Rennalls", \
@"CoCo Repass", \
@"Jessica Retter", \
@"Karl Retter", \
@"Babak Rezaei", \
@"Megan Rezaei", \
@"Kristi Rhodes", \
@"Richie Rice", \
@"Tabitha Rice", \
@"Coshack Robinson", \
@"Dustin Robinson", \
@"Eva Robinson", \
@"Jenna Rodriguez", \
@"Jonathan Rodriguez", \
@"Allie Roland", \
@"Charlie Roland", \
@"Lynn Rosete", \
@"Allison Royals", \
@"Vicki Rumer", \
@"Josh Ruud", \
@"Kelly Ruud", \
@"Marvin Salgado", \
@"Laura Sanchez", \
@"Josh Saylor", \
@"Lydia Saylor", \
@"Blake Scheideman", \
@"Claire Scheideman", \
@"Heather Schenkenfelder", \
@"Jon Schenkenfelder", \
@"Jenni Schoen", \
@"Nate Schoen", \
@"Anna Schreiner", \
@"Allison Scoggin", \
@"Zach Scoggin", \
@"Robyn Scott", \
@"Tom Scott", \
@"Brooklyn Scott", \
@"Kylie Scott", \
@"Jayden Scott", \
@"Brian Scyphers", \
@"Carmen Scyphers", \
@"Kourtney Sepulveda", \
@"Maria Sepulveda", \
@"Amy Shepherd", \
@"Paul Shepherd", \
@"Redi Shepherd", \
@"Ethan Sherer", \
@"Jennifer Sherer", \
@"Jay Shreve", \
@"Rachel Shreve", \
@"Ryan Sikes", \
@"Whitney Sikes", \
@"Daniel Sim", \
@"Laura Simmons", \
@"Robert Simmons", \
@"Hillary Sims", \
@"Marc Sims", \
@"Emily Sipes", \
@"Wesley Sipes", \
@"Lisa Sipes", \
@"Aaron Smith", \
@"Taylor Smith", \
@"Autumn Smith", \
@"Keiana Smith", \
@"Matthew Smith", \
@"Phil Smith", \
@"Terence Smith", \
@"Sawyer Smith", \
@"David Snider", \
@"Don Snider", \
@"Allison Stansbury", \
@"Cindy Starr", \
@"Bill Starr", \
@"Morgan Stemple", \
@"Angela Stephens", \
@"Kayla Stephens", \
@"J.P. Stokes", \
@"Megan Stokes", \
@"Chelsea Stone", \
@"Genevieve Stone", \
@"Jared Stone", \
@"Zach Stone", \
@"Penni Stone", \
@"Andrew Stricklin", \
@"Nicki Stricklin", \
@"Janell Stringer", \
@"Scott Stringer", \
@"Elizabeth Stringer", \
@"Hailey Stringer", \
@"Doug Sturgeon", \
@"Joy Sturgeon", \
@"Ryan Sweeney", \
@"Lesli Sweeney", \
@"Daniel Taylor", \
@"Monica Taylor", \
@"Travis Teramae", \
@"Natalie Teune", \
@"Jeanette Tilford", \
@"James Tokko", \
@"Kristi Tokko", \
@"Bryson Tokoro", \
@"Biven Toma", \
@"Sarah Toma", \
@"Andrew Tretiak", \
@"Danny Trevino", \
@"Stevie Trevino", \
@"Fernanda Trocan", \
@"Elia Trocan", \
@"Erica Truman", \
@"Adam Turner", \
@"Tiffany Turner", \
@"Jason Tyner", \
@"Sharon Tyner", \
@"Caroline Tyrell", \
@"David Tyrell", \
@"Julia Ullman", \
@"Cassie Ungaro", \
@"Andy Uyeda", \
@"Emily Vacek", \
@"Jonathan Vacek", \
@"Chanley Vaughan", \
@"Luke Vaughan", \
@"Andres Vera", \
@"Courtney Vera", \
@"Crystal Vera", \
@"Martin Vera", \
@"Jeremy Viola", \
@"Bailey Walker", \
@"Ellis Walker", \
@"Brittany Walker", \
@"Chris Walker", \
@"Nathaniel Walsh", \
@"Katie Walsh", \
@"James Walters", \
@"Natalie Walters", \
@"Stephen Wellum", \
@"Karen Wellum", \
@"Aaron White", \
@"Katie White", \
@"Randy Whitener", \
@"Scott Whitener", \
@"Stephanie Whitener", \
@"Caffy Whitney", \
@"Don Whitney", \
@"Andrew Wilkinson", \
@"Stephanie Wilkinson", \
@"Josh Wilson", \
@"Chase Winchester", \
@"Bee Wing", \
@"Stephanie Wininger", \
@"Melissa Winters", \
@"Tim Winters", \
@"Mike Withers", \
@"Patti Withers", \
@"Colleen Wolfe", \
@"Dana Wright", \
@"James Wright", \
@"Maddie Wright", \
@"Jin Yang", \
@"Carol Sun", \
@"Heather Young", \
@"Ward Young", \
@"Isaac Young", \
@"Lydia Young", \
@"Leah Young", \
@"Alyssa Yuen", \
@"Josh Yuen", \
@"Karen Zuleger"]

#endif
