//
//  Lists.h
//  Cast Lots
//
//  Created by Andy Uyeda on 7/7/17.
//  Copyright © 2017 Andy Uyeda. All rights reserved.
//

#ifndef Lists_h
#define Lists_h

#define ELDERS @[@"Ryan Fullerton", \
@"Jeff King", \
@"Donnie Isely", \
@"Ward Young", \
@"Andy Morris", \
@"Evan Calvin", \
@"Ramny Perez", \
@"Ben Hedrick", \
@"Doug Sturgeon", \
@"Dominic Cedillo", \
@"Jonny Atkinson", \
@"Jones Ndzi", \
@"Matthew Huested", \
@"Jay Ingram", \
@"Trevor Komatsu", \
@"Shingsay Lee", \
@"Tom Scott"]

#define DEACONS @[@"Ben Fennell", \
@"Kris Burns", \
@"Josh Ramirez", \
@"Rob Lauter", \
@"Andrew Perkins", \
@"Deeds Burlager", \
@"Josh Ruud"]

#define GCGLEADERS @[@"Cody Prichard", \
@"Daniel Taylor", \
@"Daniel Trevino & Miguel Contreras", \
@"Jones Ndzi", \
@"Robbie Simmons", \
@"Matt Doby", \
@"Nick Paola", \
@"Brian Scyphers & Albert Oh", \
@"David Bankes", \
@"Dave Rennalls & Shaun Martens", \
@"Kenny Fields", \
@"Jared Heinz", \
@"Andrew Perkins & Deeds Burlager", \
@"Jason Cashell", \
@"Josh Yuen & Van Michael Komatsu", \
@"Andres Vera & Kevin Gabriel", \
@"Anthony Leitner", \
@"Ben Fennell", \
@"Ben Hedrick & Ross Parmly", \
@"Donnie Isely", \
@"Ethan Ammon & Alex Jacobs", \
@"James Bufkin", \
@"Jay Ingram & Jim Hedrick", \
@"Jeremy Pelton", \
@"Josh Ramirez", \
@"Josh Ruud", \
@"Matt Mihelic", \
@"Rob Lauter", \
@"Shingsay Lee", \
@"Aaron Burkhart", \
@"Andy Bryant", \
@"Cody Gardner & Michael Lambelet", \
@"David Tyrell", \
@"Jeremy Corkum", \
@"Jordan Friesen", \
@"Kenny & Chris Komatsu", \
@"Kevin Gue", \
@"Mike Withers & Shawn Lopes", \
@"Nick Platt", \
@"Mike Stringer", \
@"Shawn Langley & Drue Corbett", \
@"Tim Winters", \
@"Chris Walker & Adam Denton", \
@"Blake Scheideman", \
@"Biven Toma & Seth Osborne"]

#define MEMBERS  @[ @"Jacob Adams", \
@"Emanuel Afzali", \
@"Henna Afzali", \
@"Jennifer Afzali", \
@"Luke Hedaiatullah Afzali", \
@"Mary Afzali", \
@"Susan Afzali", \
@"Zakia Zee Afzali", \
@"Charles Aina", \
@"Chavon Aina", \
@"Allison Allen", \
@"Craig Allen", \
@"Emily Allen", \
@"Keith Allen", \
@"Alexis Ammon", \
@"Ethan Ammon", \
@"Aaron An", \
@"Kimberly Andrews", \
@"Michael Andrews", \
@"Kristi Apostel", \
@"Shawn Apostel", \
@"Rachel Archer", \
@"Lucas Ardelean", \
@"Melissa Ardelean", \
@"Katie Arensman", \
@"Pascual Arias-Jimenez", \
@"Chello Armbrister", \
@"Celeste Arnett", \
@"AJ Aspinwall", \
@"Jordan Aspinwall", \
@"Janaye Atkinson", \
@"Jonny Atkinson", \
@"Maggie Augustin", \
@"Patrick Augustin", \
@"Caleb Aulie", \
@"Josh Austin", \
@"Dylan Bailey", \
@"Rebecca Bailey", \
@"William Ballentine", \
@"Amy Bankes", \
@"David Bankes", \
@"Kelly Bankes", \
@"Josh Barrentine", \
@"Jordan Basore", \
@"Cassie Bastidas", \
@"Hannah Baugh", \
@"Arisa Bay", \
@"Michael Becker", \
@"Sydney Becker", \
@"Bekah Bennett", \
@"Rene Bentsen", \
@"Scott Bentsen", \
@"Josh Berner", \
@"Meghan Berner", \
@"Mikaela Blando", \
@"Caitlin Blaylock", \
@"Richard Blaylock", \
@"Kim Blough", \
@"Ron Blough", \
@"Taylor Blount", \
@"Tyler Blount", \
@"Ally Borrett", \
@"Jake Bradley", \
@"Amanda Brainard", \
@"Ben Brainard", \
@"DeJuan Brents", \
@"Quincy Brents", \
@"Ramonia Brents", \
@"Kristen Brewer", \
@"Sam Brewer", \
@"Aaron Brooking", \
@"Caleb Brown", \
@"Nathan Brown", \
@"Matthew Browning", \
@"Andy Bryant", \
@"Sarah Bryant", \
@"India Bufkin", \
@"James Bufkin", \
@"Allison Bullington", \
@"Nathan Bullington", \
@"Becky Burke", \
@"Jared Burke", \
@"Kearstie Burke", \
@"Mike Burke", \
@"Aaron Burkhart", \
@"Melissa Burkhart", \
@"Deeds Burlager", \
@"Spenser Burlager", \
@"Emily Burns", \
@"Kris Burns", \
@"Isaac Busby", \
@"Rosie Buzzy", \
@"Emily Byrd", \
@"Charlie Cai", \
@"Evan Calvin", \
@"Kristin Carlton", \
@"Casey Cashell", \
@"Jason Cashell", \
@"Kristan Castro", \
@"Linh Castro", \
@"Dominic Cedillo", \
@"Rebecca Cedillo", \
@"Stephanie Chavez", \
@"Samantha Cheng", \
@"Tracey Clayton", \
@"Mackenzie Cloberdants", \
@"Carrie Cole", \
@"Ryan Cole", \
@"Shannon Collins", \
@"Gregory Collins", \
@"Andrew Colson", \
@"Nicole Colson", \
@"Whitney Conely", \
@"Kara Contreras", \
@"Miguel Contreras", \
@"Lindsey Cook", \
@"Drue Corbett", \
@"Evi Corbett", \
@"Anna Corkum", \
@"Jeremy Corkum", \
@"Cherise Cosby", \
@"Whitney Craven", \
@"Karen Culler", \
@"Karen Danka", \
@"AJ Davis", \
@"Matt Deaver", \
@"Trista Deaver", \
@"Maggie DeLoye", \
@"Adam Denton", \
@"Kellie Denton", \
@"Laura Doby", \
@"Matt Doby", \
@"Adam Dorsey", \
@"Tyriesha Doyle", \
@"Noah Drake", \
@"Eric Dubois", \
@"Kaitlin Dubois", \
@"Scott Dukes", \
@"Jon Dunn", \
@"Sam DuPlessis", \
@"Rachel Edwards", \
@"Sam Edwards", \
@"Sydney Eiseman", \
@"Kyle Eiswald", \
@"Rebekah Enarson", \
@"Ashley Endel", \
@"Ben Endel", \
@"Jennifer Ennis", \
@"Mark Ennis", \
@"Alexis Estephan", \
@"Bernard Estephan", \
@"Brenda Estephan", \
@"Charbel Estephan", \
@"Massiel Estephan", \
@"Glen Evans", \
@"Tami Evans", \
@"Anna Farthing", \
@"Cody Farthing", \
@"Ben Fennell", \
@"Naomi Fennell", \
@"Sam Ferrell", \
@"Kenny Fields", \
@"Lisa Fields", \
@"Nathan Fike", \
@"Kristy Fletcher", \
@"Zach Fletcher", \
@"Mary Beth Fletcher", \
@"Makayla Ford", \
@"Gloria Forsythe", \
@"Melody Forsythe", \
@"Abigail Fox", \
@"Kyle Fox", \
@"Eliza Frenette", \
@"Jeremy Frenette", \
@"Jordan Friesen", \
@"Mary Friesen", \
@"Christine Fuller", \
@"Christy Fullerton", \
@"Jordana Fullerton", \
@"Luke Fullerton", \
@"Ryan Fullerton", \
@"Christine Gabriel", \
@"Kevin Gabriel", \
@"Ashley Gardner", \
@"Cody Gardner", \
@"Evan Gartman", \
@"Francesca Ghiorso", \
@"Keelie Gilbert", \
@"Carrie Gladstone", \
@"R.J. Gladstone", \
@"Furman Glenn", \
@"Kayla Godbold", \
@"Heidi Gorbandt", \
@"Shane Granum", \
@"Caleb Graves", \
@"Jordan Graves", \
@"Kat Green", \
@"Sean Green", \
@"Kimberly Greenwell", \
@"Dylan Greer", \
@"Kaitlyn Greer", \
@"Ian Grigsby", \
@"Amy Gue", \
@"Bonnie Gue", \
@"Kevin Gue", \
@"Charles Gue", \
@"Johnny Gue", \
@"Beth Gurtner", \
@"Dan Gurtner", \
@"Astrid Hacker", \
@"Robert Hagerman", \
@"Samantha Hagerman", \
@"Miranda Hale", \
@"Ashley Hall", \
@"Noah Hall", \
@"Curtis Hall", \
@"Donna Hall", \
@"Katie Hancock", \
@"David Hare", \
@"Stacey Hare", \
@"Lenny Hartono", \
@"Charlotte Hazelwood", \
@"Ben Hedrick", \
@"Sarah Hedrick", \
@"Karis Hedrick", \
@"Tamara Hedrick", \
@"Jim Hedrick", \
@"Lee Ann Hedrick", \
@"Megan Heibert", \
@"Jared Heinz", \
@"Meredith Heinz", \
@"Sarah Hemby", \
@"Jeff Hemby", \
@"Chris Henderson", \
@"Chelsea Hilbert", \
@"Bethany Hildebrand", \
@"Josh Hildebrand", \
@"Jason Hill", \
@"Amy Hirby", \
@"Danny Hirby", \
@"Melissa Hoagland", \
@"Stephen Hoagland", \
@"James Holfinger", \
@"Whitney Holsteen", \
@"Aaron Holt", \
@"Felicity Holt", \
@"Yohan Hong", \
@"Derek Hougland", \
@"Donghui Hu", \
@"Aleasha Huested", \
@"Hannah Huested", \
@"Matthew Huested", \
@"Will Hulsey", \
@"Amy Ingram", \
@"Jay Ingram", \
@"Becca Isely", \
@"Donnie Isely", \
@"Linda Isham", \
@"Wayne Isham", \
@"Dani Jackson", \
@"Jon Jackson", \
@"Susan Jacobi", \
@"Alex Jacobs", \
@"Lindsey Jacobs", \
@"Delaney Jacobs", \
@"Valerie Jillson", \
@"Kimberly Jillson", \
@"Sarah Jones", \
@"Nicole Joslin", \
@"Emily Juhl", \
@"Dave Kan", \
@"Jess Kan", \
@"Stacey Kandel", \
@"Steve Keating", \
@"Valarie Keating", \
@"Paige Ketner", \
@"Rosa Kim", \
@"Andrew King", \
@"Lauren King", \
@"Jeff King", \
@"Christy King", \
@"Alexis King", \
@"Corbin Kitzmiller", \
@"Melanie Kitzmiller", \
@"Brandi Knapper", \
@"Michael Knapper", \
@"Kenny Komatsu", \
@"Sarah Komatsu", \
@"Van Michael Komatsu", \
@"Eric Krahwinkel", \
@"Hayley Krahwinkel", \
@"Kyle Francis", \
@"Gary Lamb", \
@"Jessica Lamb", \
@"Corban Lamb", \
@"Emily Lambelet", \
@"Michael Lambelet", \
@"Meredith Langley", \
@"Shawn Langley", \
@"Hannah Larkins", \
@"Rob Lauter", \
@"Sarah Lauter", \
@"Jamie LeBon", \
@"Jared LeBon", \
@"Colson Lee", \
@"Kelly Lee", \
@"Shingsay Lee", \
@"Pakou Lee", \
@"Anthony Leitner", \
@"Ashton Leitner", \
@"Dallas Leitner", \
@"Tadongrenia Longkumer", \
@"Shawn Lopes", \
@"Heidi Lopes", \
@"Herson Lopez", \
@"Austin Loveing", \
@"Holly Loveing", \
@"Margo Loveing", \
@"Wanda Lowe", \
@"Jacob Lucio", \
@"Joy Lynn", \
@"Tom Lynn", \
@"Jonathan Lyons", \
@"Claire Maday", \
@"Ronald Maday", \
@"Josiah Makram", \
@"Vilma Makram", \
@"Yaser Makram", \
@"Shania Mangum", \
@"Amy Marcum", \
@"Charlie Marcum", \
@"Bonnie Marcum", \
@"Esther Marcum", \
@"Justice Marcum", \
@"Worthy Marcum", \
@"Lindsay Marsee", \
@"Timmy Marsee", \
@"Madelyn Martens", \
@"Shaun Martens", \
@"Dylan Matthews", \
@"Jessica Matthews", \
@"Evan Matthews", \
@"Kali Matthews", \
@"Joel Maupin", \
@"Brook Maxwell", \
@"Abigail McBroom", \
@"Nathan McBroom", \
@"Michell McCollough", \
@"Alexis McDowell", \
@"Hunter McGiveney", \
@"Joey McNally", \
@"Evan McIntosh", \
@"Jena McIntosh", \
@"Bethany Meacham", \
@"Jonathan Meacham", \
@"Abbey Medley", \
@"Ethan Medley", \
@"Rachel Melson", \
@"Zack Melvin", \
@"Bethany Meredith", \
@"Laura Metcalf", \
@"Phil Metcalf", \
@"Beth Michiemo", \
@"Tim Michiemo", \
@"Matt Mihelic", \
@"Larry Millikan", \
@"Jonathan Mompoint", \
@"Blut Moo", \
@"Bethany Moore", \
@"Glen Moore", \
@"Payton Moree", \
@"Andy Morris", \
@"Emily Morris", \
@"Lazarus Morris", \
@"Anna Morris", \
@"Miriam Morris", \
@"Kenneth Moses", \
@"Laurelen Muller", \
@"Michael Muller", \
@"William Mullins", \
@"Jennifer Mullins", \
@"Kelly Nall", \
@"Chaney Nall", \
@"Jones Ndzi", \
@"Nicoline Ndzi", \
@"Eric Nerby", \
@"Kayla Nerby", \
@"Lori Nettles", \
@"Robert Nettles", \
@"Stephen O'Bryan", \
@"Barbara O'Bryan", \
@"Albert Oh", \
@"Sara Oh", \
@"Crissi Oldham", \
@"Joy Oliver", \
@"Kenny Oliver", \
@"Seth Osborne", \
@"Nick Paola", \
@"Sarah Paola", \
@"Josh Parker", \
@"Juliann Parmly", \
@"Ross Parmly", \
@"Baylee Pendleton", \
@"John Pendleton", \
@"Emmanuel Perez", \
@"Sawyer Perez", \
@"Chris Pergola", \
@"Andrew Perkins", \
@"Rachel Perkins", \
@"Liane Peters", \
@"Gloria Peterson", \
@"Kristin Peterson", \
@"Luke Peterson", \
@"Clarissa Phillips", \
@"Peter Phillips", \
@"Andy Pittman", \
@"Josh Pittman", \
@"Courtney Platt", \
@"Nick Platt", \
@"Jordan Powelson", \
@"Allison Pratt", \
@"Zach Pratt", \
@"Cody Prichard", \
@"Erica Prichard", \
@"Latevia Priddy", \
@"Joel Purvis", \
@"Abbey Ramirez", \
@"Josh Ramirez", \
@"Josh Rarick", \
@"Steven Reid", \
@"Janet Reimer", \
@"Curtis Reimer", \
@"Dave Rennalls", \
@"Jen Rennalls", \
@"CoCo Repass", \
@"Jessica Retter", \
@"Karl Retter", \
@"Babak Rezaei", \
@"Megan Rezaei", \
@"Kristi Rhodes", \
@"Coshack Robinson", \
@"Dani Robinson", \
@"Dustin Robinson", \
@"Eva Robinson", \
@"Jenna Rodriguez", \
@"Jonathan Rodriguez", \
@"Allie Roland", \
@"Charlie Roland", \
@"Allison Royals", \
@"Vicki Rumer", \
@"Josh Ruud", \
@"Kelly Ruud", \
@"Marvin Salgado", \
@"Josh Saylor", \
@"Lydia Saylor", \
@"Alexa Schaffner", \
@"Landon Schaffner", \
@"Andy Schiller", \
@"Molly Schiller", \
@"Courtney Schmidt", \
@"Joseph Schmidt", \
@"Jenni Schoen", \
@"Nate Schoen", \
@"Allison Scoggin", \
@"Zach Scoggin", \
@"Robyn Scott", \
@"Tom Scott", \
@"Brooklyn Scott", \
@"Kylie Scott", \
@"Jayden Scott", \
@"Brian Scyphers", \
@"Carmen Scyphers", \
@"Austin Segar", \
@"Taylor Segar", \
@"Kourtney Sepulveda", \
@"Maria Sepulveda", \
@"Amy Shepherd", \
@"Paul Shepherd", \
@"Redi Shepherd", \
@"Ethan Sherer", \
@"Jennifer Sherer", \
@"Jay Shreve", \
@"Rachel Shreve", \
@"Ryan Sikes", \
@"Whitney Sikes", \
@"Hillary Sims", \
@"Marc Sims", \
@"Emily Sipes", \
@"Wesley Sipes", \
@"Lisa Sipes", \
@"Aaron Smith", \
@"Taylor Smith", \
@"Courtney Smith", \
@"Autumn Smith", \
@"Keiana Smith", \
@"Phil Smith", \
@"Terence Smith", \
@"David Snider", \
@"Don Snider", \
@"Won So", \
@"Grace Soon", \
@"Allison Stansbury", \
@"Kyle Stansbury", \
@"Cindy Starr", \
@"Bill Starr", \
@"Morgan Stemple", \
@"Angela Stephens", \
@"J.P. Stokes", \
@"Megan Stokes", \
@"Zach Stone", \
@"Penni Stone", \
@"Andrew Stricklin", \
@"Nicki Stricklin", \
@"Janell Stringer", \
@"Scott Stringer", \
@"Elizabeth Stringer", \
@"Hailey Stringer", \
@"Doug Sturgeon", \
@"Joy Sturgeon", \
@"Ryan Sweeney", \
@"Lesli Sweeney", \
@"Lara Tanner", \
@"Ross Tanner", \
@"Travis Teramae", \
@"Natalie Teune", \
@"Cameron Thacker", \
@"Natalie Thacker", \
@"Van Thawng", \
@"Jeanette Tilford", \
@"James Tokko", \
@"Kristi Tokko", \
@"Bryson Tokoro", \
@"Biven Toma", \
@"Sarah Toma", \
@"Danny Trevino", \
@"Stevie Trevino", \
@"Fernanda Trocan", \
@"Elia Trocan", \
@"Adam Turner", \
@"Tiffany Turner", \
@"Jason Tyner", \
@"Sharon Tyner", \
@"Caroline Tyrell", \
@"David Tyrell", \
@"Julia Ullman", \
@"Cassie Ungaro", \
@"Andy Uyeda", \
@"Chanley Vaughan", \
@"Luke Vaughan", \
@"Andres Vera", \
@"Courtney Vera", \
@"Crystal Vera", \
@"Martin Vera", \
@"Jeremy Viola", \
@"Sarah Walje", \
@"Bailey Walker", \
@"Ellis Walker", \
@"Brittany Walker", \
@"Chris Walker", \
@"Nathaniel Walsh", \
@"Katie Walsh", \
@"James Walters", \
@"Natalie Walters", \
@"Grant Warkentin", \
@"Joel Weiland", \
@"Rebecca Weiland", \
@"Aaron White", \
@"Katie White", \
@"Randy Whitener", \
@"Scott Whitener", \
@"Stephanie Whitener", \
@"Caffy Whitney", \
@"Don Whitney", \
@"Andrew Wilkinson", \
@"Stephanie Wilkinson", \
@"Josh Wilson", \
@"Kati Wilson", \
@"Bee Wing", \
@"Melissa Winters", \
@"Tim Winters", \
@"Mike Withers", \
@"Patti Withers", \
@"Colleen Wolfe", \
@"Dana Wright", \
@"James Wright", \
@"Maddie Wright", \
@"Jin Yang", \
@"Lynn Yang", \
@"Carol Sun", \
@"Paul Yoo", \
@"Heather Young", \
@"Ward Young", \
@"Isaac Young", \
@"Lydia Young", \
@"Leah Young", \
@"Alyssa Yuen", \
@"Josh Yuen", \
@"Karen Zuleger"]

#define ITUNES1 @[@"Sumatra", \
@"Spain", \
@"China", \
@"Cameroon", \
@"Turkey", \
@"Mozambique", \
@"Nepal", \
@"Dubai", \
@"Oaxaca"]

#define ITUNES2 @[@"Matthias", \
@"Justus"]

#endif
