//
//  Lists.h
//  Cast Lots
//
//  Created by Andy Uyeda on 7/7/17.
//  Copyright © 2017 Andy Uyeda. All rights reserved.
//

#ifndef Lists_h
#define Lists_h


#define APPRENTICESHIP
#define ELDERS

#define GCGLEADERS @[@"Cody Prichard", \
@"Daniel Taylor", \
@"Daniel Trevino & Miguel Contreras", \
@"Jones Ndzi", \
@"Robbie Simmons", \
@"Matt Doby", \
@"Nick Paola", \
@"Brian Scyphers & Albert Oh", \
@"David Bankes", \
@"Dave Rennalls & Shaun Martens", \
@"Kenny Fields", \
@"Jared Heinz", \
@"Andrew Perkins & Deeds Burlager", \
@"Jason Cashell", \
@"Josh Yuen & Van Michael Komatsu", \
@"Andres Vera & Kevin Gabriel", \
@"Anthony Leitner", \
@"Ben Fennell", \
@"Ben Hedrick & Ross Parmly", \
@"Donnie Isely", \
@"Ethan Ammon & Alex Jacobs", \
@"James Bufkin", \
@"Jay Ingram & Jim Hedrick", \
@"Jeremy Pelton", \
@"Josh Ramirez", \
@"Josh Ruud", \
@"Matt Mihelic", \
@"Rob Lauter", \
@"Shingsay Lee", \
@"Aaron Burkhart", \
@"Andy Bryant", \
@"Cody Gardner & Michael Lambelet", \
@"David Tyrell", \
@"Jeremy Corkum", \
@"Jordan Friesen", \
@"Kenny & Chris Komatsu", \
@"Kevin Gue", \
@"Mike Withers & Shawn Lopes", \
@"Nick Platt", \
@"Mike Stringer", \
@"Shawn Langley & Drue Corbett", \
@"Tim Winters", \
@"Chris Walker & Adam Denton", \
@"Blake Scheideman", \
@"Biven Toma & Seth Osborne"]


#define MEMBERS  @[ @"Jacob Adams", \
@"Charles Aina", \
@"Charles Aina", \
@"Charlie Albright", \
@"Jocelyn Albright", \
@"Allison Allen", \
@"Craig Allen", \
@"Daniel Allen", \
@"Sarah Allison", \
@"Jessica Alsup", \
@"Nick Alsup", \
@"Alexis Ammon", \
@"Ethan Ammon", \
@"Kristi Apostel", \
@"Shawn Apostel", \
@"Rachel Archer", \
@"Lucas Ardelean", \
@"Melissa Ardelean", \
@"Chello Armbrister", \
@"Celeste Arnett", \
@"AJ Aspinwall", \
@"Jordan Aspinwall", \
@"Janaye Atkinson", \
@"Jonny Atkinson", \
@"Josh Austin", \
@"Eric Awbrey", \
@"Dylan Bailey", \
@"Rebecca Bailey", \
@"Timothy Balkaran", \
@"Amy Bankes", \
@"David Bankes", \
@"Kelly Bankes", \
@"Melissa Bannon", \
@"Jack Barnett", \
@"Zoe Barrow", \
@"Cassie Bastidas", \
@"Dave Bearden", \
@"Debi Bearden", \
@"Michael Becker", \
@"Rene Bentsen", \
@"Scott Bentsen", \
@"Josh Berner", \
@"Jake Berryhill", \
@"Lydia Berryhill", \
@"Mark Blake", \
@"Mikaela Blando", \
@"Caitlin Blaylock", \
@"Richard Blaylock", \
@"Lacie Bleeker", \
@"Chris Bosson", \
@"Rahel Bosson", \
@"Jake Bradley", \
@"Amanda Brainard", \
@"Ben Brainard", \
@"Ramonia Brents", \
@"Kristen Brewer", \
@"Sam Brewer", \
@"Joshua Brooks", \
@"Chavon Brown", \
@"Matthew Browning", \
@"Andy Bryant", \
@"Sarah Bryant", \
@"India Bufkin", \
@"James Bufkin", \
@"Bethel Bumanglag", \
@"Aaron Burkhart", \
@"Melissa Burkhart", \
@"Deeds Burlager", \
@"Spenser Burlager", \
@"Emily Burns", \
@"Kris Burns", \
@"Laura Burrow", \
@"Luke Burrow", \
@"Emma Busshaus", \
@"Greg Buth", \
@"Rosie Buzzy", \
@"Emily Byrd", \
@"Charlie Cai", \
@"Evan Calvin", \
@"Rachel Cameron", \
@"Michael Carlino", \
@"Casey Cashell", \
@"Jason Cashell", \
@"Dominic Cedillo", \
@"Rebecca Cedillo", \
@"Kerry Chase", \
@"Miciah Chase", \
@"Stephanie Chavez", \
@"Samantha Cheng", \
@"Heidi Childs", \
@"Shannon Chiles", \
@"Jamey Click", \
@"Matt Click", \
@"Andrew Colson", \
@"Nicole Colson", \
@"Whitney Conely", \
@"Miguel Contreras", \
@"Lindsey Cook", \
@"Korpo Cooper", \
@"Drue Corbett", \
@"Evi Corbett", \
@"Anna Corkum", \
@"Jeremy Corkum", \
@"Amber Cowan", \
@"Chris Cowan", \
@"Falcon Crosthwaite", \
@"Fred Crosthwaite", \
@"Karen Culler", \
@"Karen Danka", \
@"AJ Davis", \
@"Matt Deaver", \
@"Trista Deaver", \
@"Taron Defevers", \
@"Adam Denton", \
@"Kellie Denton", \
@"Bryan Dewaal", \
@"Laura Doby", \
@"Matt Doby", \
@"Tyriesha Doyle", \
@"Kristen Drake", \
@"Paul Drake", \
@"Maria Drake", \
@"Will Drake", \
@"Jon Dunn", \
@"Alec Eisenberg", \
@"Jamie Eisenberg", \
@"Kyle Eiswald", \
@"James Engle", \
@"Marguerite Engle", \
@"Jennifer Ennis", \
@"Mark Ennis", \
@"Alexis Estephan", \
@"Bernard Estephan", \
@"Brenda Estephan", \
@"Charbel Estephan", \
@"Massiel Estephan", \
@"Glen Evans", \
@"Tami Evans", \
@"Ben Fennell", \
@"Naomi Fennell", \
@"Sam Ferrell", \
@"Kenny Fields", \
@"Lisa Fields", \
@"Kristy Fletcher", \
@"Zach Fletcher", \
@"Mary Beth Fletcher", \
@"Gloria Forsythe", \
@"Eliza Frenette", \
@"Jeremy Frenette", \
@"Jordan Friesen", \
@"Mary Friesen", \
@"Christen Fuller", \
@"Christy Fullerton", \
@"Jordana Fullerton", \
@"Luke Fullerton", \
@"Ryan Fullerton", \
@"Christine Gabriel", \
@"Kevin Gabriel", \
@"Ashley Gardner", \
@"Cody Gardner", \
@"Evan Gartman", \
@"Megan Gates", \
@"Ben German", \
@"Carrie Gladstone", \
@"R.J. Gladstone", \
@"Furman Glenn", \
@"Kayla Godbold", \
@"Aaron Gohike", \
@"Shayna Gonzalez", \
@"Allison Gooch", \
@"Kimberly Greenwell", \
@"Katlyn Griffin", \
@"Bethany Gue", \
@"Bonnie Gue", \
@"Kevin Gue", \
@"Beth Gurtner", \
@"Dan Gurtner", \
@"Stacey Hadler", \
@"Christian Halbert", \
@"Miranda Hale", \
@"Ashley Hall", \
@"Noah Hall", \
@"Curtis Hall", \
@"Donna Hall", \
@"David Hare", \
@"Stacey Hare", \
@"Justin Harig", \
@"Jay Haynes", \
@"Melissa Haynes", \
@"Charlotte Hazelwood", \
@"Ben Hedrick", \
@"Sarah Hedrick", \
@"Tamara Hedrick", \
@"Jim Hedrick", \
@"Lee Ann Hedrick", \
@"Jared Heinz", \
@"Meredith Heinz", \
@"Pakou Lee", \
@"Edwin Hernandez", \
@"Bethany Hildebrand", \
@"Josh Hildebrand", \
@"Amy Hirby", \
@"Danny Hirby", \
@"Joanne Hirby", \
@"Melissa Hoagland", \
@"Stephen Hoagland", \
@"John Holland", \
@"Whitney Holsteen", \
@"Derek Hougland", \
@"Christina House", \
@"Jeremy House", \
@"Kyle Howard", \
@"Vy Howard", \
@"Aleasha Huested", \
@"Emily Huested", \
@"Hannah Huested", \
@"Matthew Huested", \
@"Will Hulsey", \
@"Amy Ingram", \
@"Jay Ingram", \
@"Becca Isely", \
@"Donnie Isely", \
@"Linda Isham", \
@"Wayne Isham", \
@"Dani Jackson", \
@"Jon Jackson", \
@"Susan Jacobi", \
@"Alex Jacobs", \
@"Lindsey Jacobs", \
@"Melissa Jacobs", \
@"Delaney Jacobs", \
@"Samuel Jangam", \
@"Valerie Jillson", \
@"Sarah Jones", \
@"Nicole Joslin", \
@"Emily Juhl", \
@"Dave Kan", \
@"Jess Kan", \
@"Stacey Kandel", \
@"Josh Kary", \
@"Julie Kary", \
@"Steve Keating", \
@"Valarie Keating", \
@"Anna Kesselring", \
@"John Kesselring", \
@"Diego Kim", \
@"Andrew King", \
@"Lauren King", \
@"Caleb King", \
@"Morgan King", \
@"Jeff King", \
@"Christy King", \
@"Corbing Kitzmiller", \
@"Kathryn Klein", \
@"Matthew Klein", \
@"Melanie Knapp", \
@"Brandi Knapper", \
@"Michael Knapper", \
@"Kelsey Knuth", \
@"Becky Koenig", \
@"Amber Komatsu", \
@"Chris Komatsu", \
@"Kenny Komatsu", \
@"Shawna Komatsu", \
@"Trevor Komatsu", \
@"Van Michael Komatsu", \
@"Eric Krahwinkel", \
@"Hayley Krahwinkel", \
@"Samantha Kritner", \
@"Amber Kunce", \
@"Jonathan Kuo", \
@"Kyle Francis", \
@"Emily Lambelet", \
@"Michael Lambelet", \
@"Meredith Langley", \
@"Shawn Langley", \
@"Anson Lau", \
@"Rob Lauter", \
@"Sarah Lauter", \
@"Shingsay Lee", \
@"Anthony Leitner", \
@"Dallas Leitner", \
@"Jen Li", \
@"Nicole Liesmaki", \
@"Anna Limanti", \
@"Lance Limanti", \
@"Hanna Lindsey", \
@"Amy Linzmeier", \
@"Paul Linzmeier", \
@"Josh Lohnes", \
@"Charlie Long", \
@"Tadongrenia Longkumer", \
@"Shawn Lopes", \
@"Jonathon Loren", \
@"Austin Loveing", \
@"Margo Loveing", \
@"John Lowe", \
@"Wanda Lowe", \
@"Rebecca Luna", \
@"Wayne Luna", \
@"Joy Lynn", \
@"Tom Lynn", \
@"Claire Maday", \
@"Ronald Maday", \
@"Elizabeth Madewell", \
@"Gunner Madewell", \
@"Dan Maketansky", \
@"Rebecca Maketansky", \
@"Josiah Makram", \
@"Vilma Makram", \
@"Yaser Makram", \
@"Amy Marcum", \
@"Charlie Marcum", \
@"Bonnie Marcum", \
@"Esther Marcum", \
@"Justice Marcum", \
@"Worthy Marcum", \
@"Lindsay Marsee", \
@"Timmy Marsee", \
@"Madelyn Martens", \
@"Shaun Martens", \
@"Joel Maupin", \
@"Abigail McBroom", \
@"Nathan McBroom", \
@"Eden McCarthy", \
@"Josh McCarthy", \
@"Ashley McCartney", \
@"Matt McCartney", \
@"Bekah McFarland", \
@"Drew McFarland", \
@"Corey McGalliard", \
@"Sarah McGalliard", \
@"Hunter McGiveney", \
@"Evan McIntosh", \
@"Jena McIntosh", \
@"Bethany Meacham", \
@"Jonathan Meacham", \
@"Abbey Medley", \
@"Ethan Medley", \
@"Hollie Melland", \
@"Rachel Melson", \
@"Laura Metcalf", \
@"Phil Metcalf", \
@"Matt Mihelic", \
@"Mackenzie Miller", \
@"Larry Millikan", \
@"Carmen Minton", \
@"Derek Minton", \
@"Daniel Montalvo", \
@"Bethany Moore", \
@"Glen Moore", \
@"Ashlee Morgan", \
@"Leif Morgan", \
@"Andy Morris", \
@"Emily Morris", \
@"Lazarus Morris", \
@"Anna Morris", \
@"Bethany Moxon", \
@"Matt Nagel", \
@"Lisa Nagel", \
@"Abrianna Nagel", \
@"Kelly Nall", \
@"Jones Ndzi", \
@"Nicoline Ndzi", \
@"Eric Nerby", \
@"Kayla Nerby", \
@"Lori Nettles", \
@"Robert Nettles", \
@"Hanna Newlin", \
@"Jonathan Newlin", \
@"Stephen O'Bryan", \
@"Barbara O'Bryan", \
@"Kara Odnokon", \
@"Ross Odnokon", \
@"Albert Oh", \
@"Sara Oh", \
@"Dami Oladiran", \
@"Joy Oliver", \
@"Kenny Oliver", \
@"Carol Orrick", \
@"Jim Orrick", \
@"Tim Osborn", \
@"Whitney Osborn", \
@"Seth Osborne", \
@"Amanda Ostrom", \
@"Michael Ostrom", \
@"Nick Paola", \
@"Sarah Paola", \
@"Josh Parker", \
@"Juliann Parmly", \
@"Ross Parmly", \
@"Jeremy Pelton", \
@"Lyndsey Pelton", \
@"Adam Perez", \
@"Ramny Perez", \
@"Dayi Perez", \
@"Chris Pergola", \
@"Andrew Perkins", \
@"Rachel Perkins", \
@"Gloria Peterson", \
@"Kristin Peterson", \
@"Luke Peterson", \
@"Clarissa Phillips", \
@"Peter Phillips", \
@"Taylor Pike", \
@"Maria Pinilla", \
@"Courtney Platt", \
@"Nick Platt", \
@"Cody Prichard", \
@"Latevia Priddy", \
@"Esther Prislovsky", \
@"Abbey Ramirez", \
@"Josh Ramirez", \
@"Tony Ramirez", \
@"Josh Rarick", \
@"Ivonne Rebolledo", \
@"Jose Rebollero", \
@"Dave Rennalls", \
@"Jen Rennalls", \
@"CoCo Repass", \
@"Jessica Retter", \
@"Karl Retter", \
@"Babak Rezaei", \
@"Megan Rezaei", \
@"Kristi Rhodes", \
@"Richie Rice", \
@"Tabitha Rice", \
@"Asia Richards", \
@"Erica Roberson", \
@"Coshack Robinson", \
@"Dustin Robinson", \
@"Eva Robinson", \
@"Jenna Rodriguez", \
@"Jonathan Rodriguez", \
@"Lora Rose", \
@"Allison Royals", \
@"Vicki Rumer", \
@"Josh Ruud", \
@"Kelly Ruud", \
@"Laura Sanchez", \
@"Josh Saylor", \
@"Lydia Saylor", \
@"Kathryn Schaerer", \
@"Blake Scheideman", \
@"Claire Scheideman", \
@"Heather Schenkenfelder", \
@"Jon Schenkenfelder", \
@"Jenni Schoen", \
@"Nate Schoen", \
@"Anna Schreiner", \
@"Meghan Schrock", \
@"Brendon Scoggin", \
@"Julie Scoggin", \
@"Robyn Scott", \
@"Tom Scott", \
@"Brian Scyphers", \
@"Carmen Scyphers", \
@"Nick Sevier", \
@"Kelsey Sevier", \
@"Amber Shadoan", \
@"Amy Shepherd", \
@"Paul Shepherd", \
@"Ethan Sherer", \
@"Jennifer Sherer", \
@"Jay Shreve", \
@"Laura Simmons", \
@"Robert Simmons", \
@"Hillary Sims", \
@"Marc Sims", \
@"Emily Sipes", \
@"Wesley Sipes", \
@"Lisa Sipes", \
@"Aaron Smith", \
@"Olivia Smith", \
@"Autumn Smith", \
@"Keiana Smith", \
@"Matthew Smith", \
@"Phil Smith", \
@"Terence Smith", \
@"Sarah Sparks", \
@"Fredrick Speck", \
@"Sherri Speck", \
@"Jonathan Spurgeon", \
@"Cindy Starr", \
@"Bill Starr", \
@"Angela Stephens", \
@"Kayla Stephens", \
@"Jesse Stewart", \
@"Adam Stocker", \
@"Itamara Stocker", \
@"J.P. Stokes", \
@"Megan Stokes", \
@"Chelsea Stone", \
@"Genevieve Stone", \
@"Jared Stone", \
@"Zach Stone", \
@"Penni Stone", \
@"Andrew Stricklin", \
@"Nicki Stricklin", \
@"Janell Stringer", \
@"Scott Stringer", \
@"Doug Sturgeon", \
@"Joy Sturgeon", \
@"Ryan Sweeney", \
@"Lesli Sweeney", \
@"Daniel Taylor", \
@"Monica Taylor", \
@"Travis Teramae", \
@"Natalie Teune", \
@"Jeanette Tilford", \
@"James Tokko", \
@"Kristi Tokko", \
@"Bryson Tokoro", \
@"Biven Toma", \
@"Sarah Toma", \
@"Trevor Tomlinson", \
@"Andrew Tretiak", \
@"Danny Trevino", \
@"Stevie Trevino", \
@"Fernanda Trocan", \
@"Erica Truman", \
@"Adam Turner", \
@"Tiffany Turner", \
@"Jason Tyner", \
@"Sharon Tyner", \
@"Caroline Tyrell", \
@"David Tyrell", \
@"Robin Uhlott", \
@"Cassie Ungaro", \
@"Andy Uyeda", \
@"Emily Vacek", \
@"Jonathan Vacek", \
@"Jisun Van Engelenhoven", \
@"Paul Van Engelenhoven", \
@"Chanley Vaughan", \
@"Luke Vaughan", \
@"Andres Vera", \
@"Courtney Vera", \
@"Crystal Vera", \
@"Martin Vera", \
@"Jeremy Viola", \
@"Sarah Walje", \
@"Bailey Walker", \
@"Ellis Walker", \
@"Brittany Walker", \
@"Chris Walker", \
@"Dan Wallace", \
@"Nathaniel Walsh", \
@"James Walters", \
@"Natalie Walters", \
@"Stephen Wellum", \
@"Karen Wellum", \
@"Aaron White", \
@"Katie White", \
@"Randy Whitener", \
@"Scott Whitener", \
@"Stephanie Whitener", \
@"Caffy Whitney", \
@"Don Whitney", \
@"Andrew Wilkinson", \
@"Stephanie Wilkinson", \
@"Rhonda Wilkinson", \
@"Melissa Winters", \
@"Tim Winters", \
@"Mike Withers", \
@"Patti Withers", \
@"Colleen Wolfe", \
@"Ben Woodward", \
@"Sarah Woodward", \
@"Dana Wright", \
@"James Wright", \
@"Maddie Wright", \
@"Jack Yager", \
@"Carol Sun", \
@"Heather Young", \
@"Ward Young", \
@"Isaac Young", \
@"Lydia Young", \
@"Leah Young", \
@"Alyssa Yuen", \
@"Josh Yuen", \
@"Karen Zuleger"]


#endif
